css-two-column-layout - Alex Gonzalez
gonzalez-alex/c1022-code-solutions pull request #23
Opened 2022-10-14 19:32 UTC by gonzalez-alex

<img width="1280" alt="css-two-column-layout" src="https://user-images.githubusercontent.com/113146217/195927405-a24486c7-bcc7-42c6-8f7a-8d190d6af622.png">

2022-10-14 21:09 UTC, codingcodymiller requested changes

2022-10-14 21:09 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +  </div>
You should never have empty columns in a layout class system to create space. Instead, make a class that you can apply to the `row` that utilizes `justify-content` to place the single `column` with content in the center.

2022-10-14 22:54 UTC, gonzalez-alex commented on css-two-column-layout/index.html
> +  </div>
ah ic, that makes things much simpler.. haha def overthought that one..

2022-10-16 00:24 UTC, gonzalez-alex commented
<img width="638" alt="css-two-column-layout" src="https://user-images.githubusercontent.com/113146217/196012240-3f5f0172-67ee-493f-91fa-72839d67b7c7.png">

2022-10-17 18:23 UTC, codingcodymiller approved these changes
Nice work!

2022-10-17 18:50 UTC, merged